# Generated by Django 3.0 on 2020-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Description (e.g. Food - Vegetarian Meal', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('short_description', models.TextField(help_text='Enter a short description of the retreat', max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the retreat', max_length=1000)),
                ('host', models.TextField(help_text='Enter a description of the facilitator if there is one', max_length=500)),
                ('facilities', models.ManyToManyField(help_text='Select the Facilities Present', to='retreats.Facility')),
            ],
        ),
    ]
