# Generated by Django 3.0 on 2020-05-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Enter a description of the retreat', max_length=1500),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.TextField(blank=True, help_text='Enter a description of the facilitator if there is one', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(help_text='Enter a short description of the retreat', max_length=350),
        ),
    ]
