# Generated by Django 3.0 on 2020-05-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0002_auto_20200510_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
    ]
