# Generated by Django 3.0 on 2020-05-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0003_remove_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.TextField(blank=True, help_text='Enter a description of the facilitator if there is one', max_length=500, null=True),
        ),
    ]
