# Generated by Django 3.0 on 2020-05-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0004_event_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.TextField(blank=True, help_text='Enter a description of the schedule if there is one', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.TextField(blank=True, help_text='Enter a description of the facilitator if there is one', max_length=1000, null=True),
        ),
    ]
