# Generated by Django 3.0 on 2020-05-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0006_event_picture_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='home_image',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
