# Generated by Django 3.0 on 2020-05-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0007_event_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='home_image',
            field=models.ImageField(blank=True, default='img/yoga.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.OneToOneField(help_text='Select an image or upload a new one', null=True, on_delete=django.db.models.deletion.CASCADE, to='retreats.Image'),
        ),
    ]
