# Generated by Django 3.0 on 2020-05-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0008_auto_20200528_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
