# Generated by Django 3.0 on 2020-05-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0011_auto_20200528_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facilities',
            field=models.ManyToManyField(blank=True, help_text='Select the Facilities Present', to='retreats.Facility'),
        ),
    ]
